### ISSUE TITLE
AttributeError: 'HDF5Dataset' object has no attribute 'H'

### ISSUE THREAD

**Issue by jxxtin** [ArmanMaesumi/OneNoise#1]
Hi, thanks for your amazing work @ArmanMaesumi !

During training process, i got the small error as below

I think the part that declares self.H, self.W is missing. 

How we set them to?

```Traceback (most recent call last):
  File "/mnt/personal/justin/OneNoise/train.py", line 44, in <module>
    run(arguments)
  File "/mnt/personal/justin/OneNoise/train.py", line 23, in run
    trainer = Trainer(
              ^^^^^^^^
  File "/mnt/personal/justin/OneNoise/trainer.py", line 75, in __init__
    self.create_dataloader(config, rank, world_size, train_batch_size)
  File "/mnt/personal/justin/OneNoise/trainer.py", line 113, in create_dataloader
    self.ds = HDF5Dataset(
              ^^^^^^^^^^^^
  File "/mnt/personal/justin/OneNoise/noise_data.py", line 130, in __init__
    self.data = np.empty((nimages // world_size, self.H, self.W), dtype=np.uint8)
                                                 ^^^^^^
AttributeError: 'HDF5Dataset' object has no attribute 'H'
```

**Comment by jxxtin** [comment]
set   `self.H = self.W = 256` solve the issue

**Comment by ArmanMaesumi** [comment]
Ah, thanks for catching this! I must've deleted those hardcoded variables before pushing. 

It should be fixed now.
